test: fmt
	go test -race  ./controller/test/...
	go test -race  ./service/checker/...
	go test -race  ./service/sql_util/...
	go test -race  ./util/...

build: fmt
	mkdir -p bin
	go build -o bin/dbinjection .

build-linux: fmt
	CGO_ENABLED=0 GOOS=linux go build -a -ldflags '-extldflags "-static"' .

fmt:
	go fmt ./...